# Generated by Django 3.0.3 on 2020-03-08 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0003_goalattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalAttemptEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_in_time_period', models.BooleanField(default=False)),
                ('goal_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goals.GoalAttempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
