# Generated by Django 3.0.3 on 2020-03-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goalattemptentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalchallenge',
            name='difficulty',
            field=models.CharField(default='EASY', max_length=30),
        ),
    ]
